services:
  flask-app:
    build:
      context: ./app
    environment:
      FLASK_ENV: development
      MYSQL_HOST: mysql-db
      MYSQL_PORT: 3306
      MYSQL_USER: mydb
      MYSQL_PASSWORD: password
      MYSQL_DB: todoapp
    ports:
      - "5789:5789"
    depends_on:
      - mysql-db
    volumes:
      - ./:/usr/src/app

  mysql-db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: todoapp
      MYSQL_USER: mydb
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: {}
